language: php

php:
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar update -v




script:
  - Vendors/bin/phpunit --coverage-text --configuration  Tests/Conf/phpunit.xml Tests
  - Vendors/bin/phpunit --coverage-xml shippable/codecoverage/  Tests/Virus Total/*.php
  
notifiacations:
  email: false
