language:
  php

php:
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar update -v



script:
  - Vendors/bin/phpunit --coverage-text --configuration Tests/Conf/phpunit.xml 
  - Vendors/bin/phpunit --coverage-xml --configuration Tests/Conf/phpunit.xml Tests
  
notifications:
  email: false
